/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import modelo.pessoaLogin;
import persistencia.ConexaoBanco;
import utilidades.Conversao;
/**
 *
 * @author Renan
 */
public class GUICadUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadUsuario
     */
    public GUICadUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param pLogin
     * @throws java.sql.SQLException
     */
    @SuppressWarnings("unchecked")
    
    
    
    public void cadastrarLogin(pessoaLogin pLogin) throws SQLException {
        
        //Buscando uma conexão com o Banco de Dados
        Connection con = ConexaoBanco.getConexao();
        /*Criando obj. capaz de executar instruções
         SQL no banco de dados*/
        Statement stat = con.createStatement();

        try {
            
	   //get current date time with Date()
            
            //String que receberá instrução SQL
            String sql;
            /* Montando a instrução INSERT para inserir
             um objeto pVO no Banco MySQL 
            USAR ASPAS SIMPLES PARA ESCAPE DO TIPO STRING*/
            sql = "insert into usuario"
                    +"(user_nome,user_senha,email)"
                    +"values ('"
                    +pLogin.getLogin()+"',"
                    +"'"+pLogin.getSenha()+"',"
                    +"'"+pLogin.getEmail()+"')";

            //Executando o sql
            stat.execute(sql);
        } catch (SQLException e) {
            //throw new SQLException("Erro ao inserir produto!");
            JOptionPane.showMessageDialog(rootPane, "Erro! "+e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            con.close();
                stat.close();
        }//fecha finally
    }//fecha método
    
    private void cadastrar(){
        
        try {
            
            pessoaLogin pLogin = new pessoaLogin();         
            pLogin.setLogin(jtCadLogin.getText());
            pLogin.setSenha(jtCadSenha.getText());
            pLogin.setEmail(jtCadEmail.getText());
            
            cadastrarLogin(pLogin);
            JOptionPane.showMessageDialog(rootPane, "Usuário cadastrado com sucesso! ", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro!"+e.getMessage());
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtCadEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtCadSenha = new javax.swing.JPasswordField();
        jlCadLogin = new javax.swing.JLabel();
        jlCadSenha = new javax.swing.JLabel();
        jlCadEmail = new javax.swing.JLabel();
        jtCadLogin = new javax.swing.JTextField();

        setTitle("Cadastrar Usuário");

        jtCadEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCadEmailKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jLabel4.setText("Insira seus dados para cadastro:");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlCadLogin.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        jlCadLogin.setText("Login:");

        jlCadSenha.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        jlCadSenha.setText("Senha:");

        jlCadEmail.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        jlCadEmail.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCadLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtCadLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jbCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCadSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlCadEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCadEmail)
                            .addComponent(jtCadSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCadLogin)
                    .addComponent(jtCadLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCadSenha)
                    .addComponent(jtCadSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCadEmail)
                    .addComponent(jtCadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();

    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtCadEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCadEmailKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cadastrar();
        }
    }//GEN-LAST:event_jtCadEmailKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlCadEmail;
    private javax.swing.JLabel jlCadLogin;
    private javax.swing.JLabel jlCadSenha;
    private javax.swing.JTextField jtCadEmail;
    private javax.swing.JTextField jtCadLogin;
    private javax.swing.JPasswordField jtCadSenha;
    // End of variables declaration//GEN-END:variables
}
