/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.io.File;
import javax.swing.JOptionPane;
import modelo.Teste;
import utilidades.GeraPDF;


/**

 */
public class GuiGeraPDFTextoDigitado extends javax.swing.JInternalFrame {

    /* Instanciando objeto para receber os dados  da tela*/
    Teste t = new Teste();
    
    /**
     * Creates new form GuiGeraPDFTextoDigitado
     */
    public GuiGeraPDFTextoDigitado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jcomboEstadoCivil = new javax.swing.JComboBox();
        jsliderAvaliacao = new javax.swing.JSlider();
        jpfSenha = new javax.swing.JPasswordField();
        jspinnerQuantidade = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtObservacao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbGerarPDF = new javax.swing.JButton();
        jbLer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerador de PDF");
        setToolTipText("");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel1.setText("Nome");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(30, 20, 60, 14);

        jLabel2.setText("Estado Civil");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(320, 80, 100, 14);

        jLabel3.setText("Avaliação");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(20, 80, 80, 14);
        jLayeredPane1.add(jtNome);
        jtNome.setBounds(70, 10, 220, 30);

        jcomboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "solteiro", "casado", "divorciado" }));
        jLayeredPane1.add(jcomboEstadoCivil);
        jcomboEstadoCivil.setBounds(390, 70, 80, 30);

        jsliderAvaliacao.setMajorTickSpacing(10);
        jsliderAvaliacao.setPaintLabels(true);
        jsliderAvaliacao.setPaintTicks(true);
        jsliderAvaliacao.setToolTipText("");
        jLayeredPane1.add(jsliderAvaliacao);
        jsliderAvaliacao.setBounds(70, 70, 210, 70);
        jLayeredPane1.add(jpfSenha);
        jpfSenha.setBounds(70, 40, 220, 30);

        jspinnerQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jLayeredPane1.add(jspinnerQuantidade);
        jspinnerQuantidade.setBounds(390, 20, 60, 30);

        jtObservacao.setColumns(20);
        jtObservacao.setRows(5);
        jScrollPane1.setViewportView(jtObservacao);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 150, 400, 100);

        jLabel4.setText("Senha");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(30, 50, 70, 14);

        jLabel5.setText("Observação");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(20, 150, 110, 14);

        jLabel6.setText("Quantidade");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(320, 20, 100, 14);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jbGerarPDF.setText("Gerar PDF");
        jbGerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarPDFActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbGerarPDF);
        jbGerarPDF.setBounds(0, 0, 140, 30);

        jbLer.setText("Ler PDF");
        jbLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jbLer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addComponent(jbLer, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receberDados() {
        try {

            /* Buscando nome do componente JTextField */
            t.setNome(jtNome.getText());
            /* Buscando senha do componente JPasswordField */
            t.setSenha(String.valueOf(jpfSenha.getPassword()));
            /* Buscando estado civil do componente JComboBox */
            t.setEstadocivil(String.valueOf(jcomboEstadoCivil.getSelectedItem()));
            /* Buscando avaliação do comp. JSlider */
            t.setValor(jsliderAvaliacao.getValue());
            /* Buscando obs do comp. JTextArea */
            t.setObservacao(jtObservacao.getText());
            /* Buscando qtd do comp. JSpinner */
            t.setQtd((int) jspinnerQuantidade.getValue());
            
         
            JOptionPane.showMessageDialog(
                    this,
                    "Dados cadastrados com sucesso!"
                  + "\n"+t.toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch

    }//fecha método

    
    public void gerarPDF(){
        try {
             /* Também podemos pedir para o usuário o nome que ele deseja colocar
               no arquivo PDF através de um JOptionPane.showInputDialog */
            String nomePDF = JOptionPane.showInputDialog(this, 
                                    "Digite o nome que deseja para o arquivo de PDF");
            
            //Opcional, método que altera o nome do PDF.
            GeraPDF.setNomePDF(nomePDF);
            //GeraPDF.setNomePDF("arquivo1"); Nome fixo

            //Método que gera um arquivo PDF.
            GeraPDF.gerarPDF(t);
            
            
            JOptionPane.showMessageDialog(this, 
                    "PDF gerado com sucesso!"
                  + "\nNome do arquivo gerado: "+nomePDF);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    
    }//fecha método
    
    
    public void lerPDF(){
        try {
            String nomePDF = JOptionPane.showInputDialog(this,"Digite o nome do PDF que você deseja abrir:","Abrir",JOptionPane.INFORMATION_MESSAGE);
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            desktop.open(new File ("D:\\java\\produtoModelo\\pdfGerado\\"+nomePDF+".pfd"));
            
            
        } catch (Exception e) {
        }
    }
    private void jbGerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarPDFActionPerformed
        receberDados();
        gerarPDF();
        dispose();
    }//GEN-LAST:event_jbGerarPDFActionPerformed

    private void jbLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLerActionPerformed
        lerPDF();
    }//GEN-LAST:event_jbLerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGerarPDF;
    private javax.swing.JButton jbLer;
    private javax.swing.JComboBox jcomboEstadoCivil;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JSlider jsliderAvaliacao;
    private javax.swing.JSpinner jspinnerQuantidade;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextArea jtObservacao;
    // End of variables declaration//GEN-END:variables
}
