/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import java.awt.event.KeyEvent;
import static javax.management.Query.gt;

/**
 *
 * @author Leandro / Renan
 */
public class IframeSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form Isobre
     */
    public IframeSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    /*
 private void abrirGuiTeste() {
        IframeInputtext gi = new IframeInputtext();

        jAreadeTrabalho.add(gi);

        gi.setVisible(true);
        gi.setClosable(true);   //simbolo de fechar janela
        gi.setIconifiable(true); //simbolo de minimizar
        gi.setMaximizable(true); //simbolo de maximizar janela
        gi.setLocation(30, 20);  // posicionar janela

    }
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Créditos");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Chiller", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X Leandro X");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 170, 410, 80);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("programmed by:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 10, 410, 80);

        jLabel4.setFont(new java.awt.Font("Chiller", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("x Renan x");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 110, 410, 80);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 3, 24)); // NOI18N
        jLabel5.setText("Data: 28/04/2015");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 320, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/matrix.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
